/* Generated by AN DISI Unibo */ 
package it.unibo.qarobot3;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qarobot3 extends QActorMsgQueue{
	public MsgHandle_Qarobot3(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
