/* Generated by AN DISI Unibo */ 
package it.unibo.qahuelampemulatoractivator;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qahuelampemulatoractivator extends QActorMsgQueue{
	public MsgHandle_Qahuelampemulatoractivator(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
