/* Generated by AN DISI Unibo */ 
package it.unibo.qaledproban;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qaledproban extends QActorMsgQueue{
	public MsgHandle_Qaledproban(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
