/* Generated by AN DISI Unibo */ 
package it.unibo.consoleCtx;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evhdeletemap extends AbstractEvhdeletemap { 
	public Evhdeletemap(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
