/* Generated by AN DISI Unibo */ 
package it.unibo.qamockmsgsender;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qamockmsgsender extends QActorMsgQueue{
	public MsgHandle_Qamockmsgsender(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
