/* Generated by AN DISI Unibo */ 
package it.unibo.qaselfmsg;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qaselfmsg extends QActorMsgQueue{
	public MsgHandle_Qaselfmsg(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
