/* Generated by AN DISI Unibo */ 
package it.unibo.qamindofrobotproban;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qamindofrobotproban extends QActorMsgQueue{
	public MsgHandle_Qamindofrobotproban(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
