/* Generated by AN DISI Unibo */ 
package it.unibo.qabusinesslogicproban;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qabusinesslogicproban extends QActorMsgQueue{
	public MsgHandle_Qabusinesslogicproban(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
