/* Generated by AN DISI Unibo */ 
package it.unibo.qaproximitysensor;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qaproximitysensor extends QActorMsgQueue{
	public MsgHandle_Qaproximitysensor(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
