/* Generated by AN DISI Unibo */ 
package it.unibo.progCtx;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evhtime extends AbstractEvhtime { 
	public Evhtime(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
