/* Generated by AN DISI Unibo */ 
package it.unibo.qafrontendactivator;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qafrontendactivator extends QActorMsgQueue{
	public MsgHandle_Qafrontendactivator(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
