/* Generated by AN DISI Unibo */ 
package it.unibo.qarobotproban;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qarobotproban extends QActorMsgQueue{
	public MsgHandle_Qarobotproban(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
