/* Generated by AN DISI Unibo */ 
package it.unibo.qabusinesslogic;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractQabusinesslogic extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractQabusinesslogic(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/qabusinesslogic/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/qabusinesslogic/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("handleEnvEvent",handleEnvEvent);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "qabusinesslogic tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_init",0);
	     pr.incNumIter(); 	
	    	String myselfName = "init";  
	    	//bbb
	     msgTransition( pr,myselfName,"qabusinesslogic_"+myselfName,false,
	          new StateFun[]{stateTab.get("handleEnvEvent"), stateTab.get("handleEnvEvent") }, 
	          new String[]{"true","E","timeEvent", "true","E","tempEvent" },
	          40000000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun handleEnvEvent = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleEnvEvent",-1);
	    	String myselfName = "handleEnvEvent";  
	    	printCurrentEvent(false);
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("timeEvent(V)");
	    	if( currentEvent != null && currentEvent.getEventId().equals("timeEvent") && 
	    		pengine.unify(curT, Term.createTerm("timeEvent(VALUE)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg  ="curTimeValue(X)";
	    			String parg1 ="curTimeValue(V)";
	    			/* ReplaceRule */
	    			parg = updateVars(Term.createTerm("timeEvent(VALUE)"),  Term.createTerm("timeEvent(V)"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			parg1 = updateVars(Term.createTerm("timeEvent(VALUE)"),  Term.createTerm("timeEvent(V)"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg1);
	    			if( parg != null && parg1 != null  ) replaceRule(parg, parg1);	    		  					
	    	}
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("tempEvent(V)");
	    	if( currentEvent != null && currentEvent.getEventId().equals("tempEvent") && 
	    		pengine.unify(curT, Term.createTerm("tempEvent(VALUE)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg  ="curTemperatureValue(X)";
	    			String parg1 ="curTemperatureValue(V)";
	    			/* ReplaceRule */
	    			parg = updateVars(Term.createTerm("tempEvent(VALUE)"),  Term.createTerm("tempEvent(V)"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			parg1 = updateVars(Term.createTerm("tempEvent(VALUE)"),  Term.createTerm("tempEvent(V)"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg1);
	    			if( parg != null && parg1 != null  ) replaceRule(parg, parg1);	    		  					
	    	}
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?evalTime(good)" )) != null ){
	    	{//actionseq
	    	temporaryStr = "\"GOOD time range, doing nothing.\"";
	    	println( temporaryStr );  
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?evalTemperature(cold)" )) != null ){
	    	{//actionseq
	    	temporaryStr = "\"Temperature is nice, doing nothing.\"";
	    	println( temporaryStr );  
	    	temporaryStr = "rTempAndTimeOk";
	    	addRule( temporaryStr );  
	    	};//actionseq
	    	}
	    	else{ {//actionseq
	    	temporaryStr = "\"Temperature too hot, stopping everything.\"";
	    	println( temporaryStr );  
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "environmentalEventViolation(REASON)","environmentalEventViolation(\"bad_temp\")", guardVars ).toString();
	    	emit( "environmentalEventViolation", temporaryStr );
	    	temporaryStr = "rTempKo";
	    	addRule( temporaryStr );  
	    	};//actionseq
	    	}};//actionseq
	    	}
	    	else{ {//actionseq
	    	temporaryStr = "\"BAD time range, stopping everything.\"";
	    	println( temporaryStr );  
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "environmentalEventViolation(REASON)","environmentalEventViolation(\"bad_time\")", guardVars ).toString();
	    	emit( "environmentalEventViolation", temporaryStr );
	    	temporaryStr = "rTimeKo";
	    	addRule( temporaryStr );  
	    	};//actionseq
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"qabusinesslogic_"+myselfName,false,true);
	    }catch(Exception e_handleEnvEvent){  
	    	 println( getName() + " plan=handleEnvEvent WARNING:" + e_handleEnvEvent.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleEnvEvent
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
