/* Generated by AN DISI Unibo */ 
package it.unibo.qasoffrittirobot;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qasoffrittirobot extends QActorMsgQueue{
	public MsgHandle_Qasoffrittirobot(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
