/* Generated by AN DISI Unibo */ 
package it.unibo.qabusinesslogic;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qabusinesslogic extends QActorMsgQueue{
	public MsgHandle_Qabusinesslogic(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
