/* Generated by AN DISI Unibo */ 
package it.unibo.qafrontend;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qafrontend extends QActorMsgQueue{
	public MsgHandle_Qafrontend(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
