/* Generated by AN DISI Unibo */ 
package it.unibo.qaconsole3;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qaconsole3 extends QActorMsgQueue{
	public MsgHandle_Qaconsole3(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
