/* Generated by AN DISI Unibo */ 
package it.unibo.qacityinformationproban;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qacityinformationproban extends QActorMsgQueue{
	public MsgHandle_Qacityinformationproban(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
